// <auto-generated />
using System;
using DDCatalogue.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDCatalogue.Migrations
{
    [DbContext(typeof(DDContext))]
    [Migration("20200603172800_Made NPC Fields JArrays")]
    partial class MadeNPCFieldsJArrays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int?>("Charisma")
                        .HasColumnType("int");

                    b.Property<int?>("Constitution")
                        .HasColumnType("int");

                    b.Property<int?>("Dexterity")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HitDice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int?>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proficiencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reactions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("Subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Creature");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Creature");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beliefs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Flaws")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("int");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteableEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.HasIndex("MonsterId");

                    b.ToTable("Npcs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Background = "Raised with his three brothers, Klarg was below average intelligence to say the least. Always playing Kings and Queens, he became obsessed with being the ruler of a country. He forged his own crown, and took over a goblin bandit gang declaring himself as their King.|Klarg has since made a deal with Iarno to steal supplies from Phandalin and to resupply the Redbrands instead.",
                            LocaleId = 9,
                            MonsterId = 2,
                            Name = "Klarg BigCrown",
                            NoteableEvents = "[\"Made a deal with the party for Yeemik's head\",\"Killed by the party\"]",
                            Picture = "Klarg_BigCrown.jpg"
                        },
                        new
                        {
                            Id = 2,
                            LocaleId = 3,
                            MonsterId = 1,
                            Name = "Gundren Rockseeker"
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 9,
                            LocaleId = 6,
                            MonsterId = 3,
                            Name = "Sildar Hallwinter"
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 2,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Elmar Barthen"
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 4,
                            LocaleId = 6,
                            MonsterId = 3,
                            Name = "Linene Graywind"
                        },
                        new
                        {
                            Id = 6,
                            LocaleId = 9,
                            MonsterId = 4,
                            Name = "Yeemik Largebrain"
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 10,
                            LocaleId = 6,
                            Name = "Iarno Albrek"
                        },
                        new
                        {
                            Id = 8,
                            LocaleId = 6,
                            MonsterId = 1,
                            Name = "Tharden Rockseeker"
                        },
                        new
                        {
                            Id = 9,
                            LocaleId = 6,
                            MonsterId = 1,
                            Name = "Nundro Rockseeker"
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = 1,
                            LocaleId = 6,
                            MonsterId = 7,
                            Name = "Toblen Stonehill",
                            Picture = "Toblen_Stonehill.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BuildingId = 3,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Daran Edermath"
                        },
                        new
                        {
                            Id = 12,
                            BuildingId = 5,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Halia Thornton"
                        },
                        new
                        {
                            Id = 13,
                            BuildingId = 6,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Qelline Alderleaf"
                        },
                        new
                        {
                            Id = 14,
                            BuildingId = 7,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Sister Garaele"
                        },
                        new
                        {
                            Id = 15,
                            BuildingId = 9,
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Harbin Wester"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterBuilding", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("MonsterId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("MonsterBuilding");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterLocale", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("LocaleId")
                        .HasColumnType("int");

                    b.HasKey("MonsterId", "LocaleId");

                    b.HasIndex("LocaleId");

                    b.ToTable("MonsterLocale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocaleId")
                        .HasColumnType("int");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocaleId = 6,
                            Name = "Stonehill Inn"
                        },
                        new
                        {
                            Id = 2,
                            LocaleId = 6,
                            Name = "Barthen's Provisions"
                        },
                        new
                        {
                            Id = 3,
                            LocaleId = 6,
                            Name = "Edermath Orchard"
                        },
                        new
                        {
                            Id = 4,
                            LocaleId = 6,
                            Name = "Lionshield Coster"
                        },
                        new
                        {
                            Id = 5,
                            LocaleId = 6,
                            Name = "Phandalin Miner's Exchange"
                        },
                        new
                        {
                            Id = 6,
                            LocaleId = 6,
                            Name = "Alderleaf Farm"
                        },
                        new
                        {
                            Id = 7,
                            LocaleId = 6,
                            Name = "Shrine of Luck"
                        },
                        new
                        {
                            Id = 8,
                            LocaleId = 6,
                            Name = "The Sleeping Giant"
                        },
                        new
                        {
                            Id = 9,
                            LocaleId = 6,
                            Name = "Townmaster's Hall"
                        },
                        new
                        {
                            Id = 10,
                            LocaleId = 6,
                            Map = "Tresendar_Manor.png",
                            Name = "Tresendar Manor"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Map")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Map")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.ToTable("Dungeons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cragmaw Hideout"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Locale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Locales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neverwinter"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thundertree"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cragmaw Castle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Conyberry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Old Owl Well"
                        },
                        new
                        {
                            Id = 6,
                            Map = "Phandalin.png",
                            Name = "Phandalin",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Leilon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Neverwinter"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cragmaw Hideout"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Map = "Sword_Coast_North.png",
                            Name = "Sword Coast North"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Monster", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Creatures.Creature");

                    b.Property<string>("Actions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("float");

                    b.Property<string>("LegendaryActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassivePerception")
                        .HasColumnType("int");

                    b.Property<string>("Senses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialAbilities")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Monster");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alignment = 0,
                            ArmorClass = 16,
                            Charisma = 10,
                            Constitution = 14,
                            Dexterity = 11,
                            HitPoints = 39,
                            Intelligence = 10,
                            Languages = "Common, Dwarvish",
                            Name = "Drawf Warrior",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":25,\"Measurement\":\"ft\"}]",
                            Strength = 14,
                            Wisdom = 11,
                            ChallengeRating = 1.0,
                            PassivePerception = 10,
                            Senses = "{\"darkvision\":\"60 ft.\"}"
                        },
                        new
                        {
                            Id = 2,
                            Alignment = 8,
                            ArmorClass = 16,
                            Charisma = 9,
                            Constitution = 13,
                            Dexterity = 14,
                            HitDice = "5d8",
                            HitPoints = 27,
                            Intelligence = 8,
                            Languages = "Common, Goblin",
                            Name = "Bugbear",
                            Proficiencies = "[{\"name\":\"Skill: Stealth\",\"value\":6},{\"name\":\"Skill: Survival\",\"value\":2}]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 15,
                            Subtype = "goblinoid",
                            Type = "humanoid",
                            Wisdom = 11,
                            Actions = "[{\"name\":\"Morningstar\",\"desc\":\"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage.\",\"attack_bonus\":4,\"damage\":[{\"damage_type\":{\"name\":\"Piercing\"},\"damage_dice\":\"2d8\",\"damage_bonus\":2}]},{\"name\":\"Javelin\",\"desc\":\"Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range.\",\"attack_bonus\":4,\"damage\":[{\"damage_type\":{\"name\":\"Piercing\"},\"damage_dice\":\"2d6\",\"damage_bonus\":2}]}]",
                            ChallengeRating = 1.0,
                            PassivePerception = 10,
                            Senses = "{\"darkvision\":\"60 ft.\"}",
                            SpecialAbilities = "[{\"name\":\"Brute\",\"desc\":\"A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).\"},{\"name\":\"Surprise Attack\",\"desc\":\"If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack.\"}]"
                        },
                        new
                        {
                            Id = 3,
                            Alignment = 9,
                            ArmorClass = 18,
                            Charisma = 15,
                            Constitution = 14,
                            Dexterity = 11,
                            HitPoints = 52,
                            Intelligence = 11,
                            Languages = "Any one",
                            Name = "Knight",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 16,
                            Wisdom = 11,
                            ChallengeRating = 3.0,
                            PassivePerception = 10
                        },
                        new
                        {
                            Id = 4,
                            Alignment = 5,
                            ArmorClass = 15,
                            Charisma = 8,
                            Constitution = 10,
                            Dexterity = 14,
                            HitPoints = 7,
                            Intelligence = 10,
                            Languages = "Common, Goblin",
                            Name = "Goblin",
                            Size = "Small",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 8,
                            Wisdom = 8,
                            ChallengeRating = 0.25,
                            PassivePerception = 9
                        },
                        new
                        {
                            Id = 5,
                            Alignment = 9,
                            ArmorClass = 10,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 4,
                            Intelligence = 10,
                            Languages = "Any one",
                            Name = "Commoner",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 10,
                            Wisdom = 10,
                            ChallengeRating = 0.0,
                            PassivePerception = 10
                        },
                        new
                        {
                            Id = 6,
                            Alignment = 10,
                            ArmorClass = 13,
                            Charisma = 6,
                            Constitution = 12,
                            Dexterity = 15,
                            HitPoints = 11,
                            Intelligence = 3,
                            Languages = "",
                            Name = "Wolf",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":40,\"Measurement\":\"ft\"}]",
                            Strength = 12,
                            Wisdom = 12,
                            ChallengeRating = 0.25,
                            PassivePerception = 13
                        },
                        new
                        {
                            Id = 7,
                            Alignment = 0,
                            ArmorClass = 14,
                            Charisma = 10,
                            Constitution = 12,
                            Dexterity = 10,
                            HitPoints = 26,
                            Intelligence = 10,
                            Languages = "Common, Dwarvish",
                            Name = "Dwarf",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":25,\"Measurement\":\"ft\"}]",
                            Strength = 13,
                            Wisdom = 12,
                            ChallengeRating = 0.5,
                            PassivePerception = 10
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Player", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Creatures.Creature");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Faction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Armour", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Armour");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Treasure", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Treasure");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Weapon", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Npc", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Npcs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Npcs")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Npcs")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterBuilding", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Monsters")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Buildings")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterLocale", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Monsters")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Locales")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Building", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Buildings")
                        .HasForeignKey("LocaleId");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Dungeon", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Dungeons")
                        .HasForeignKey("LocaleId");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Locale", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Region", "Region")
                        .WithMany("Locales")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Region", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Continent", "Continent")
                        .WithMany("Regions")
                        .HasForeignKey("ContinentId");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Player", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Players")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Players")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
