// <auto-generated />
using System;
using DDCatalogue.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DDCatalogue.Migrations
{
    [DbContext(typeof(DDContext))]
    partial class DDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Alignment")
                        .HasColumnType("integer");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HitDice")
                        .HasColumnType("text");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Proficiencies")
                        .HasColumnType("text");

                    b.Property<string>("Reactions")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .HasColumnType("text");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Creature");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Creature");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<string>("Beliefs")
                        .HasColumnType("text");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Flaws")
                        .HasColumnType("text");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<int?>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NoteableEvents")
                        .HasColumnType("text");

                    b.Property<string>("Passions")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.HasIndex("MonsterId");

                    b.ToTable("Npcs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Background = "Raised with his three brothers, Klarg was below average intelligence to say the least. Always playing Kings and Queens, he became obsessed with being the ruler of a country. He forged his own crown, and took over a goblin bandit gang declaring himself as their King.|Klarg has since made a deal with Iarno to steal supplies from Phandalin and to resupply the Redbrands instead.",
                            Beliefs = "[]",
                            Flaws = "[]",
                            LocaleId = 9,
                            MonsterId = 2,
                            Name = "Klarg BigCrown",
                            NoteableEvents = "[\"Made a deal with the party for Yeemik's head\",\"Killed by the party\"]",
                            Passions = "[]",
                            Picture = "Klarg_BigCrown.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Background = "",
                            Beliefs = "[]",
                            Flaws = "[]",
                            LocaleId = 3,
                            MonsterId = 1,
                            Name = "Gundren Rockseeker",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 3,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 9,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 3,
                            Name = "Sildar Hallwinter",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 4,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 2,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Elmar Barthen",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 5,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 4,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 3,
                            Name = "Linene Graywind",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 6,
                            Background = "",
                            Beliefs = "[]",
                            Flaws = "[]",
                            LocaleId = 9,
                            MonsterId = 4,
                            Name = "Yeemik Largebrain",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 7,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 10,
                            Flaws = "[]",
                            LocaleId = 6,
                            Name = "Iarno Albrek",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 8,
                            Background = "",
                            Beliefs = "[]",
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 1,
                            Name = "Tharden Rockseeker",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 9,
                            Background = "",
                            Beliefs = "[]",
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 1,
                            Name = "Nundro Rockseeker",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 10,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 1,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 7,
                            Name = "Toblen Stonehill",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = "Toblen_Stonehill.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 3,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Daran Edermath",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 12,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 5,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Halia Thornton",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 13,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 6,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Qelline Alderleaf",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 14,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 7,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Sister Garaele",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        },
                        new
                        {
                            Id = 15,
                            Background = "",
                            Beliefs = "[]",
                            BuildingId = 9,
                            Flaws = "[]",
                            LocaleId = 6,
                            MonsterId = 5,
                            Name = "Harbin Wester",
                            NoteableEvents = "[]",
                            Passions = "[]",
                            Picture = ""
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.BuildingMap", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Coords")
                        .HasColumnType("text");

                    b.HasKey("BuildingId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("BuildingMap");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            MapId = 1,
                            Coords = "[1830,3083]"
                        },
                        new
                        {
                            BuildingId = 2,
                            MapId = 1,
                            Coords = "[1107,3735]"
                        },
                        new
                        {
                            BuildingId = 3,
                            MapId = 1,
                            Coords = "[1041,876]"
                        },
                        new
                        {
                            BuildingId = 4,
                            MapId = 1,
                            Coords = "[2280,2300]"
                        },
                        new
                        {
                            BuildingId = 5,
                            MapId = 1,
                            Coords = "[3101,2115]"
                        },
                        new
                        {
                            BuildingId = 6,
                            MapId = 1,
                            Coords = "[2971,4447]"
                        },
                        new
                        {
                            BuildingId = 7,
                            MapId = 1,
                            Coords = "[1656,2445]"
                        },
                        new
                        {
                            BuildingId = 8,
                            MapId = 1,
                            Coords = "[1913,4396]"
                        },
                        new
                        {
                            BuildingId = 9,
                            MapId = 1,
                            Coords = "[2382,2836]"
                        },
                        new
                        {
                            BuildingId = 10,
                            MapId = 1,
                            Coords = "[1351,6418]"
                        },
                        new
                        {
                            BuildingId = 1,
                            MapId = 2,
                            Coords = "[1830,3083]"
                        },
                        new
                        {
                            BuildingId = 2,
                            MapId = 2,
                            Coords = "[1107,3735]"
                        },
                        new
                        {
                            BuildingId = 3,
                            MapId = 2,
                            Coords = "[1041,876]"
                        },
                        new
                        {
                            BuildingId = 4,
                            MapId = 2,
                            Coords = "[2280,2300]"
                        },
                        new
                        {
                            BuildingId = 5,
                            MapId = 2,
                            Coords = "[3101,2115]"
                        },
                        new
                        {
                            BuildingId = 6,
                            MapId = 2,
                            Coords = "[2971,4447]"
                        },
                        new
                        {
                            BuildingId = 7,
                            MapId = 2,
                            Coords = "[1656,2445]"
                        },
                        new
                        {
                            BuildingId = 8,
                            MapId = 2,
                            Coords = "[1913,4396]"
                        },
                        new
                        {
                            BuildingId = 9,
                            MapId = 2,
                            Coords = "[2382,2836]"
                        },
                        new
                        {
                            BuildingId = 10,
                            MapId = 2,
                            Coords = "[1351,6418]"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterBuilding", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.HasKey("MonsterId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("MonsterBuilding");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterLocale", b =>
                {
                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("LocaleId")
                        .HasColumnType("integer");

                    b.HasKey("MonsterId", "LocaleId");

                    b.HasIndex("LocaleId");

                    b.ToTable("MonsterLocale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<string>("Map")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocaleId = 6,
                            Name = "Stonehill Inn"
                        },
                        new
                        {
                            Id = 2,
                            LocaleId = 6,
                            Name = "Barthen's Provisions"
                        },
                        new
                        {
                            Id = 3,
                            LocaleId = 6,
                            Name = "Edermath Orchard"
                        },
                        new
                        {
                            Id = 4,
                            LocaleId = 6,
                            Name = "Lionshield Coster"
                        },
                        new
                        {
                            Id = 5,
                            LocaleId = 6,
                            Name = "Phandalin Miner's Exchange"
                        },
                        new
                        {
                            Id = 6,
                            LocaleId = 6,
                            Name = "Alderleaf Farm"
                        },
                        new
                        {
                            Id = 7,
                            LocaleId = 6,
                            Name = "Shrine of Luck"
                        },
                        new
                        {
                            Id = 8,
                            LocaleId = 6,
                            Name = "The Sleeping Giant"
                        },
                        new
                        {
                            Id = 9,
                            LocaleId = 6,
                            Name = "Townmaster's Hall"
                        },
                        new
                        {
                            Id = 10,
                            LocaleId = 6,
                            Map = "Tresendar_Manor.png",
                            Name = "Tresendar Manor"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Map")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faerun"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Dungeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Map")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.ToTable("Dungeons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cragmaw Hideout"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Locale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Locales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neverwinter",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thundertree",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cragmaw Castle",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Conyberry",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Old Owl Well",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Phandalin",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Leilon",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Neverwinter",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cragmaw Hideout",
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Center")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Variation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "PhanDawn.jpg",
                            LocaleId = 6,
                            Name = "Phandalin_Dawn",
                            Variation = "Dawn"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "PhanDay.jpg",
                            LocaleId = 6,
                            Name = "Phandalin_Day",
                            Variation = "Day"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "PhanNight.jpg",
                            LocaleId = 6,
                            Name = "Phandalin_Night",
                            Variation = "Night"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContinentId")
                        .HasColumnType("integer");

                    b.Property<string>("Map")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentId = 1,
                            Map = "Sword_Coast_North.png",
                            Name = "Sword Coast North"
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Monster", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Creatures.Creature");

                    b.Property<string>("Actions")
                        .HasColumnType("text");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("double precision");

                    b.Property<string>("LegendaryActions")
                        .HasColumnType("text");

                    b.Property<int>("MonsterType")
                        .HasColumnType("integer");

                    b.Property<int>("PassivePerception")
                        .HasColumnType("integer");

                    b.Property<string>("Senses")
                        .HasColumnType("text");

                    b.Property<string>("SpecialAbilities")
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Monster");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alignment = 0,
                            ArmorClass = 16,
                            Charisma = 10,
                            Constitution = 14,
                            Dexterity = 11,
                            HitDice = "",
                            HitPoints = 39,
                            Intelligence = 10,
                            Languages = "Common, Dwarvish",
                            Name = "Drawf Warrior",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":25,\"Measurement\":\"ft\"}]",
                            Strength = 14,
                            Wisdom = 11,
                            Actions = "[]",
                            ChallengeRating = 1.0,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 10,
                            Senses = "{\"darkvision\":\"60 ft.\"}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        },
                        new
                        {
                            Id = 2,
                            Alignment = 8,
                            ArmorClass = 16,
                            Charisma = 9,
                            Constitution = 13,
                            Dexterity = 14,
                            HitDice = "5d8",
                            HitPoints = 27,
                            Intelligence = 8,
                            Languages = "Common, Goblin",
                            Name = "Bugbear",
                            Picture = "bugbear.jpeg",
                            Proficiencies = "[{\"name\":\"Skill: Stealth\",\"value\":6},{\"name\":\"Skill: Survival\",\"value\":2}]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 15,
                            Wisdom = 11,
                            Actions = "[{\"name\":\"Morningstar\",\"desc\":\"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage.\",\"attack_bonus\":4,\"damage\":[{\"damage_type\":{\"name\":\"Piercing\"},\"damage_dice\":\"2d8\",\"damage_bonus\":2}]},{\"name\":\"Javelin\",\"desc\":\"Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range.\",\"attack_bonus\":4,\"damage\":[{\"damage_type\":{\"name\":\"Piercing\"},\"damage_dice\":\"2d6\",\"damage_bonus\":2}]}]",
                            ChallengeRating = 1.0,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 10,
                            Senses = "{\"darkvision\":\"60 ft.\"}",
                            SpecialAbilities = "[{\"name\":\"Brute\",\"desc\":\"A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).\"},{\"name\":\"Surprise Attack\",\"desc\":\"If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack.\"}]",
                            Xp = 200
                        },
                        new
                        {
                            Id = 3,
                            Alignment = 9,
                            ArmorClass = 18,
                            Charisma = 15,
                            Constitution = 14,
                            Dexterity = 11,
                            HitDice = "",
                            HitPoints = 52,
                            Intelligence = 11,
                            Languages = "Any one",
                            Name = "Knight",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 16,
                            Wisdom = 11,
                            Actions = "[]",
                            ChallengeRating = 3.0,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 10,
                            Senses = "{}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        },
                        new
                        {
                            Id = 4,
                            Alignment = 5,
                            ArmorClass = 15,
                            Charisma = 8,
                            Constitution = 10,
                            Dexterity = 14,
                            HitDice = "",
                            HitPoints = 7,
                            Intelligence = 10,
                            Languages = "Common, Goblin",
                            Name = "Goblin",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Small",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 8,
                            Wisdom = 8,
                            Actions = "[]",
                            ChallengeRating = 0.25,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 9,
                            Senses = "{}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        },
                        new
                        {
                            Id = 5,
                            Alignment = 9,
                            ArmorClass = 10,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitDice = "",
                            HitPoints = 4,
                            Intelligence = 10,
                            Languages = "Any one",
                            Name = "Commoner",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":30,\"Measurement\":\"ft\"}]",
                            Strength = 10,
                            Wisdom = 10,
                            Actions = "[]",
                            ChallengeRating = 0.0,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 10,
                            Senses = "{}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        },
                        new
                        {
                            Id = 6,
                            Alignment = 10,
                            ArmorClass = 13,
                            Charisma = 6,
                            Constitution = 12,
                            Dexterity = 15,
                            HitDice = "",
                            HitPoints = 11,
                            Intelligence = 3,
                            Languages = "",
                            Name = "Wolf",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":40,\"Measurement\":\"ft\"}]",
                            Strength = 12,
                            Wisdom = 12,
                            Actions = "[]",
                            ChallengeRating = 0.25,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 13,
                            Senses = "{}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        },
                        new
                        {
                            Id = 7,
                            Alignment = 0,
                            ArmorClass = 14,
                            Charisma = 10,
                            Constitution = 12,
                            Dexterity = 10,
                            HitDice = "",
                            HitPoints = 26,
                            Intelligence = 10,
                            Languages = "Common, Dwarvish",
                            Name = "Dwarf",
                            Picture = "",
                            Proficiencies = "[]",
                            Reactions = "[]",
                            Size = "Medium",
                            Speed = "[{\"Name\":\"walk\",\"Value\":25,\"Measurement\":\"ft\"}]",
                            Strength = 13,
                            Wisdom = 12,
                            Actions = "[]",
                            ChallengeRating = 0.5,
                            LegendaryActions = "[]",
                            MonsterType = 14,
                            PassivePerception = 10,
                            Senses = "{}",
                            SpecialAbilities = "[]",
                            Xp = 0
                        });
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Player", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Creatures.Creature");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<int?>("LocaleId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.HasIndex("BuildingId");

                    b.HasIndex("LocaleId");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Armour", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Armour");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Treasure", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Treasure");
                });

            modelBuilder.Entity("DDCatalogue.Model.Items.Weapon", b =>
                {
                    b.HasBaseType("DDCatalogue.Model.Items.Item");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Npc", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Npcs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Npcs")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Npcs")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("Locale");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.BuildingMap", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Maps")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDCatalogue.Model.Locations.Map", "Map")
                        .WithMany("Buildings")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterBuilding", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Monsters")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Buildings")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("DDCatalogue.Model.Joins.MonsterLocale", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Monsters")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDCatalogue.Model.Creatures.Monster", "Monster")
                        .WithMany("Locales")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locale");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Building", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Buildings")
                        .HasForeignKey("LocaleId");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Dungeon", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Dungeons")
                        .HasForeignKey("LocaleId");

                    b.Navigation("Building");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Locale", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Region", "Region")
                        .WithMany("Locales")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Map", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Maps")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Region", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Continent", "Continent")
                        .WithMany("Regions")
                        .HasForeignKey("ContinentId");

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Player", b =>
                {
                    b.HasOne("DDCatalogue.Model.Locations.Building", "Building")
                        .WithMany("Players")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DDCatalogue.Model.Locations.Locale", "Locale")
                        .WithMany("Players")
                        .HasForeignKey("LocaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Building");

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Building", b =>
                {
                    b.Navigation("Maps");

                    b.Navigation("Monsters");

                    b.Navigation("Npcs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Continent", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Locale", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Dungeons");

                    b.Navigation("Maps");

                    b.Navigation("Monsters");

                    b.Navigation("Npcs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Map", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("DDCatalogue.Model.Locations.Region", b =>
                {
                    b.Navigation("Locales");
                });

            modelBuilder.Entity("DDCatalogue.Model.Creatures.Monster", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Locales");

                    b.Navigation("Npcs");
                });
#pragma warning restore 612, 618
        }
    }
}
